// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class PriceRecommender
{
    /// <summary>
    /// model input class for PriceRecommender.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"Category")]
        public string Category { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Calories")]
        public float Calories { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"prep_time")]
        public float Prep_time { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"production_cost")]
        public float Production_cost { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"selling_price")]
        public float Selling_price { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for PriceRecommender.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        //[ColumnName(@"Category")]
        //public float[] Category { get; set; }

        [ColumnName(@"Calories")]
        public float Calories { get; set; }

        [ColumnName(@"prep_time")]
        public float Prep_time { get; set; }

        [ColumnName(@"production_cost")]
        public float Production_cost { get; set; }

        //[ColumnName(@"selling_price")]
        //public float Selling_price { get; set; }

        //[ColumnName(@"Features")]
        //public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("PriceRecommender.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
